# Generated by Django 5.0.2 on 2024-02-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_event_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='akiliroom',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
